events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend:8080; # проксирую на бэкенд по имени сервиса 

            proxy_set_header Host $host;    # передаю настоящий hostname 
            proxy_set_header X-Real-IP $remote_addr;    # передаю настощий IP пользователя
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;    # передаю цепочку IP запроса
        }
    }
}